IF
    True()
THEN
    RESPONSE #100
        CutSceneId(Player1)
        SetGlobal("CbTagGame","AR3500",1)
        Wait(2)
        ApplySpellRES("CBIMOENL","CBIMOENL") // Imoen
        ApplySpellRES("CBIMOENL",Player1) // Imoen
        ActionOverride("CBIMOENL",MoveToPointNoInterrupt([4264.846]))
        MoveViewPoint([4226.880],VERY_FAST)
        Wait(1)
        MoveToPoint([4255.840])
        Wait(100)
END