IF
	Global("ButtonsDisabled","AR3501",0)
        OR(6)
	     Class(Protagonist,DRUID_ALL)
	     Class(Protagonist,CLERIC_ALL)
	     Class(Protagonist,PALADIN_ALL)
	     Class(Protagonist,MAGE_ALL)
	     Class(Protagonist,BARD_ALL)
	     Class(Protagonist,MAGE_ALL)
	!Kit(Protagonist,INQUISITOR)
THEN
	RESPONSE #100
		ForceSpellRES("CBCHOR_S",Protagonist)
  	        SetGlobal("ButtonsDisabled","AR3501",1)
  	        Continue()
END

