IF
	True()
THEN
	RESPONSE #100
		CutSceneId("CBCWLTCH")
		FadeToColor([20.0],0)
		Wait(4)
		SetGlobal("CbTumblingWizardTaught","AR0709",3)
		SetGlobal("CbTumblingWizardWantsCure","GLOBAL",4)
		SetGlobal("CbTumblingWizardAdvancedMemory","LOCALS",1)
		DayNight(16)
		ApplySpellRES("CBCWTHM1",LastTalkedToBy(Myself))
		Wait(2)
		FadeFromColor([20.0],0)
		StartDialogueNoSet(LastTalkedToBy(Myself))
END


