IF
	Global("HaerDalisFree","GLOBAL",1)
	GlobalGT("CbScreening_NoName","AR0510",1)
THEN
	RESPONSE #100
		DestroySelf()
END

IF
	GlobalGT("PlayOver","AR0510",0)
	GlobalGT("CbScreening_NoName","AR0510",1)
	See([PC])
THEN
	RESPONSE #100
		MoveToPoint([363.1120])
		EscapeArea()
END

IF
	GlobalGT("PlayOver","AR0510",0)
	GlobalGT("CbScreening_NoName","AR0510",1)
	!See([PC])
THEN
	RESPONSE #100
		DestroySelf()
END