IF
	OR(2)
		Entered([ANYONE])
		Opened([ANYONE])
THEN
	RESPONSE #100
		DisplayString(LastTrigger,14381) // Trap Sprung
		ForceSpell(LastTrigger,TRAP_ARROW_DETONATION)
		Wait(1)
		ForceSpell(LastTrigger,TRAP_ARROW_DETONATION)
		Wait(1)
		ForceSpell(LastTrigger,TRAP_ARROW_DETONATION)
		Wait(1)
		ForceSpell(LastTrigger,TRAP_ARROW_DETONATION)
		Wait(1)
		ForceSpell(LastTrigger,TRAP_ARROW_DETONATION)
		Wait(1)
		ForceSpell(LastTrigger,TRAP_ARROW_DETONATION)
		Wait(1)
		ForceSpell(LastTrigger,TRAP_ARROW_DETONATION)
		Wait(1)
		ForceSpell(LastTrigger,TRAP_ARROW_DETONATION)
		Wait(1)
		ForceSpell(LastTrigger,TRAP_ARROW_DETONATION)
		Wait(1)
		ForceSpell(LastTrigger,TRAP_ARROW_DETONATION)
END


