IF
	OnCreation()
THEN
	RESPONSE #100
		FaceObject("CB596SE1")
END

IF
	Global("CbTaxAnnouncement","GLOBAL",5)
THEN
	RESPONSE #25
		Wait(5)
		EscapeArea()
	RESPONSE #25
		Wait(10)
		EscapeArea()
	RESPONSE #25
		Wait(15)
		EscapeArea()
	RESPONSE #25
		Wait(25)
		EscapeArea()
END

IF
	OR(4)
		See("CBTAXAS1")
		See("CBTAXAS2")
		See("CBTAXAS3")
		See("CBTAXAS4")
        HPGT(LastSeenBy(Myself),0)
THEN
	RESPONSE #100
		Attack(LastSeenBy(Myself))
END


