IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player2)
		FadeToColor([20.0],0)
		Wait(2)
		StartMovie("RESTINN")
		Wait(2)
		DayNight(3)
		IncrementGlobal("CbPlayer2DiseasedByCowl","GLOBAL",1)
		SetGlobalTimer("CbPlayer2DiseasedDay","GLOBAL",ONE_DAY)
		Rest()
		SetGlobal("CbTumblingWizardWantsStaff","GLOBAL",1)
		FadeFromColor([20.0],0)
		Wait(1)
		ActionOverride("CBCWLTCH",StartDialogueNoSet(Player2))
END


