IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player5)
		FadeToColor([20.0],0)
		Wait(2)
		StartMovie("RESTINN")
		Wait(2)
		DayNight(3)
		IncrementGlobal("CbPlayer5DiseasedByCowl","GLOBAL",1)
		SetGlobalTimer("CbPlayer5DiseasedDay","GLOBAL",ONE_DAY)
		Rest()
		SetGlobal("CbTumblingWizardWantsCure","GLOBAL",1)
		Wait(1)
		FadeFromColor([20.0],0)
		Wait(1)
		ActionOverride("CBCWLTCH",StartDialogueNoSet(Player5))
END


