IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player6)
		FadeToColor([20.0],0)
		Wait(2)
		StartMovie("RESTINN")
		Wait(2)
		DayNight(3)
		IncrementGlobal("CbPlayer6DiseasedByCowl","GLOBAL",1)
		SetGlobalTimer("CbPlayer6DiseasedDay","GLOBAL",ONE_DAY)
		Rest()
		SetGlobal("CbTumblingWizardWantsResearch","GLOBAL",1)
		Wait(1)
		FadeFromColor([20.0],0)
		Wait(1)
		ActionOverride("CBCWLTCH",StartDialogueNoSet(Player6))
END


