IF
	Clicked([ANYONE])
	Range(LastTrigger,10)
THEN
	RESPONSE #100
		DisplayString(Myself,@550131) // When you touch the golden star, you get the feeling you have done something right.
		SetGlobal("Star2","AR3637",1)
		PlaySound("EFF_M62")
		TriggerActivation("Star2",FALSE)
END

IF
	Clicked([ANYONE])
	!Range(LastTrigger,10)
THEN
	RESPONSE #100
		DisplayString(Myself,14702) // You are too far away to use that.
END


